### ISSUE TITLE
ImportError: No module named 'dns.exception'

### ISSUE THREAD

**Issue by nickahoy** [zalando-stups/stups-cli#3]
STUPS tooling is failing for me due to a failure to import `dns.exception`:

``` bash
~ ❯❯❯ sudo pip3 install --upgrade stups
Password:
The directory '/Users/nbell/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/nbell/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: stups in /usr/local/lib/python3.5/site-packages
Requirement already up-to-date: click in /usr/local/lib/python3.5/site-packages (from stups)
Requirement already up-to-date: stups-fullstop in /usr/local/lib/python3.5/site-packages (from stups)
Requirement already up-to-date: stups-pierone in /usr/local/lib/python3.5/site-packages (from stups)
Requirement already up-to-date: stups-cli-support in /usr/local/lib/python3.5/site-packages (from stups)
Requirement already up-to-date: stups-kio in /usr/local/lib/python3.5/site-packages (from stups)
Requirement already up-to-date: stups-piu in /usr/local/lib/python3.5/site-packages (from stups)
Requirement already up-to-date: stups-zign in /usr/local/lib/python3.5/site-packages (from stups)
Requirement already up-to-date: stups-senza in /usr/local/lib/python3.5/site-packages (from stups)
Requirement already up-to-date: stups-mai in /usr/local/lib/python3.5/site-packages (from stups)
Requirement already up-to-date: clickclick>=1.0 in /usr/local/lib/python3.5/site-packages (from stups-fullstop->stups)
Requirement already up-to-date: requests in /usr/local/lib/python3.5/site-packages (from stups-fullstop->stups)
Requirement already up-to-date: dnspython3 in /usr/local/lib/python3.5/site-packages (from stups-cli-support->stups)
Requirement already up-to-date: PyYAML in /usr/local/lib/python3.5/site-packages (from stups-cli-support->stups)
Requirement already up-to-date: botocore>=1.4.10 in /usr/local/lib/python3.5/site-packages (from stups-piu->stups)
Requirement already up-to-date: pyperclip in /usr/local/lib/python3.5/site-packages (from stups-piu->stups)
Requirement already up-to-date: boto3>=1.3.0 in /usr/local/lib/python3.5/site-packages (from stups-piu->stups)
Requirement already up-to-date: stups-tokens in /usr/local/lib/python3.5/site-packages (from stups-zign->stups)
Requirement already up-to-date: keyring in /usr/local/lib/python3.5/site-packages (from stups-zign->stups)
Requirement already up-to-date: keyrings.alt in /usr/local/lib/python3.5/site-packages (from stups-zign->stups)
Requirement already up-to-date: pytest>=2.7.3 in /usr/local/lib/python3.5/site-packages (from stups-senza->stups)
Requirement already up-to-date: raven in /usr/local/lib/python3.5/site-packages (from stups-senza->stups)
Requirement already up-to-date: pystache in /usr/local/lib/python3.5/site-packages (from stups-senza->stups)
Requirement already up-to-date: typing in /usr/local/lib/python3.5/site-packages (from stups-senza->stups)
Requirement already up-to-date: aws-saml-login>=0.9 in /usr/local/lib/python3.5/site-packages (from stups-mai->stups)
Requirement already up-to-date: dnspython==1.15.0 in /usr/local/lib/python3.5/site-packages (from dnspython3->stups-cli-support->stups)
Requirement already up-to-date: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python3.5/site-packages (from botocore>=1.4.10->stups-piu->stups)
Requirement already up-to-date: docutils>=0.10 in /usr/local/lib/python3.5/site-packages (from botocore>=1.4.10->stups-piu->stups)
Requirement already up-to-date: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.5/site-packages (from botocore>=1.4.10->stups-piu->stups)
Requirement already up-to-date: s3transfer<0.2.0,>=0.1.0 in /usr/local/lib/python3.5/site-packages (from boto3>=1.3.0->stups-piu->stups)
Requirement already up-to-date: py>=1.4.29 in /usr/local/lib/python3.5/site-packages (from pytest>=2.7.3->stups-senza->stups)
Requirement already up-to-date: contextlib2 in /usr/local/lib/python3.5/site-packages (from raven->stups-senza->stups)
Requirement already up-to-date: beautifulsoup4>=4.3.2 in /usr/local/lib/python3.5/site-packages (from aws-saml-login>=0.9->stups-mai->stups)
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python3.5/site-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.4.10->stups-piu->stups)
~ ❯❯❯ stups

  ___ _____ _   _ ___  ___
 / __|_   _| | | | _ \/ __| by ZALANDO
 \__ \ | | | |_| |  _/\__ \
 |___/ |_|  \___/|_|  |___/

 STUPS - To Unleash Penguin Swarms

 Homepage:      https://stups.io
 Documentation: https://docs.stups.io
 GitHub Repos:  https://github.com/zalando-stups

Do you want to configure the STUPS CLI tools now? [Y/n]: y
Traceback (most recent call last):
  File "/usr/local/bin/stups", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/stups/cli.py", line 24, in main
    import stups_cli.config
  File "/usr/local/lib/python3.5/site-packages/stups_cli/config.py", line 2, in <module>
    import dns.exception
ImportError: No module named 'dns.exception'
```

Packages are being installed to the right location:

``` bash
~ ❯❯❯ which pip3                                                                                                                                                               
/usr/local/bin/pip3
~ ❯❯❯ pip3 --version
pip 8.1.2 from /usr/local/lib/python3.5/site-packages (python 3.5)
~ ❯❯❯
```

`dns.exception` is a module of the `dnspython` package, which is also installed in the right location:

``` bash
~ ❯❯❯ pip3 install --upgrade dnspython
Requirement already up-to-date: dnspython in /usr/local/lib/python3.5/site-packages
```

Note: installing STUPS with `sudo -H` makes no difference.

**Comment by mikkeloscar** [comment]
Try:

```
$ pip3 install --force-reinstall --upgrade dnspython
```

**Comment by nickahoy** [comment]
Thanks! That seems to have worked. But why?
